- name: Preparation
  hosts: ptvserver
  become: yes
  tasks:
  - name: Fetch a GPG key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add docker.com official apt
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present
  - name: Update index
    apt:
        update_cache: yes
  - name: Upgrade packages
    apt:
        upgrade: yes
  - name: Install multiple packages
    apt:
        name:
        - build-essential
        - cmake
        - dkms
        - curl
        - git
        - unzip
        - language-pack-ja
        - wireless-tools
        - hostapd
        - network-manager
        - zsh
        - avahi-daemon
        - alsa-base
        - alsa-utils
        - shairport-sync
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin
        - docker-ce-rootless-extras
        - uidmap
        - dbus-user-session
  - name: Install docker rootless
    become: no
    command: |
      dockerd-rootless-setuptool.sh install
      echo 'export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock' >> /home/{{ansible_user}}/.bashrc
