- name: Audio
  hosts: ptvserver
  tasks:
  - name: Configure shairport-sync
    become: yes
    command:
        chdir: /etc
        argv:
            - sed
            - "-ie"
            - s/default/makemono/g
            - shairport-sync.conf
  - name: Upload ALSA config
    become: yes
    copy: src=../files/asound.conf dest=/etc/asound.conf
  - name: Add the existing user "{{ ansible_user }}" to group sudo
    user:
      name: "{{ ansible_user }}"
      groups: audio
      append: yes
    become: yes

