- name: Compose a container
  hosts: ptvserver
  tasks:
  - name: Upload recipes
    copy: src=../files/docker/ dest=/home/{{ansible_user}}/docker/
  - name: Flush custom config files
    become: no
    copy: src=../config/ dest=/home/{{ansible_user}}/docker/mirakurun/config/
  - name: Configure ssh agent forwarding
    become: yes
    shell: echo "AllowAgentForwarding yes" > /etc/ssh/sshd_config.d/ansible_config.conf
  - name: First spawning
    become: yes
    shell: |
      export DOCKER_HOST=unix:///run/user/$(id {{ansible_user}} -u)/docker.sock
      docker compose run --rm -e SETUP=true mirakurun --build
    args:
      chdir: docker/
  - name: Restart container
    become: yes
    shell: |
      export DOCKER_HOST=unix:///run/user/$(id {{ansible_user}} -u)/docker.sock
      docker compose down
      docker compose up -d
    args:
      chdir: docker/
