version: "3.7"
networks:
  default:
    name: mirakurun
services:
  mirakurun:
    build:
      context: .
      dockerfile: Dockerfile
    image: maleicacid/mirakurun
    container_name: mirakurun
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    environment:
      TZ: Asia/Tokyo
      # LOG_LEVEL: "3"
      # DEBUG: "true"
    ports:
      - 40772:40772
      # - 9229:9229
    devices:
      - /dev/bus:/dev/bus
 #     - /dev/dvb:/dev/dvb
      - /dev/px4video0:/dev/px4video0
      - /dev/px4video1:/dev/px4video1
      - /dev/px4video2:/dev/px4video2
      - /dev/px4video3:/dev/px4video3
    volumes:
      - /home/kazuki/docker/mirakurun/run/:/var/run/
      - /home/kazuki/docker/mirakurun/opt/:/opt/
      - /home/kazuki/docker/mirakurun/config/:/app-config/
      - /home/kazuki/docker/mirakurun/data/:/app-data/
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m
