- name: Ｊ：ＣＯＭテレビ
  type: GR
  channel: '13'
- name: ＴＯＫＹＯ　ＭＸ１
  type: GR
  channel: '16'
- name: ｔｖｋ１
  type: GR
  channel: '18'
- name: フジテレビ
  type: GR
  channel: '21'
- name: ＴＢＳ１
  type: GR
  channel: '22'
- name: テレビ東京１
  type: GR
  channel: '23'
- name: テレビ朝日
  type: GR
  channel: '24'
- name: 日テレ１
  type: GR
  channel: '25'
- name: ＮＨＫ総合１・東京
  type: GR
  channel: '27'
- name: Ｊ：ＣＯＭチャンネル
  type: GR
  channel: '46'
- name: ＢＳ朝日１
  type: BS
  channel: BS01_0
  serviceId: 151
- name: ＢＳ朝日２
  type: BS
  channel: BS01_0
  serviceId: 152
- name: ＢＳ朝日３
  type: BS
  channel: BS01_0
  serviceId: 153
- name: ＢＳ－ＴＢＳ
  type: BS
  channel: BS01_1
  serviceId: 161
- name: ＢＳ－ＴＢＳ
  type: BS
  channel: BS01_1
  serviceId: 162
- name: ＢＳ－ＴＢＳ
  type: BS
  channel: BS01_1
  serviceId: 163
- name: ＢＳテレ東
  type: BS
  channel: BS01_2
  serviceId: 171
- name: ＢＳテレ東２
  type: BS
  channel: BS01_2
  serviceId: 172
- name: ＢＳテレ東３
  type: BS
  channel: BS01_2
  serviceId: 173
- name: ＷＯＷＯＷプライム
  type: BS
  channel: BS03_0
  serviceId: 191
- name: ＮＨＫＢＳプレミアム
  type: BS
  channel: BS03_1
  serviceId: 103
- name: ＮＨＫＢＳプレミアム
  type: BS
  channel: BS03_1
  serviceId: 104
- name: ＷＯＷＯＷライブ
  type: BS
  channel: BS05_0
  serviceId: 192
- name: ＷＯＷＯＷシネマ
  type: BS
  channel: BS05_1
  serviceId: 193
- name: ＷＯＷＯＷライブ
  type: BS
  channel: BS05_2
  serviceId: 192
- name: ＢＳ１１イレブン
  type: BS
  channel: BS09_0
  serviceId: 211
- name: スターチャンネル１
  type: BS
  channel: BS09_1
  serviceId: 200
- name: ＢＳ１２トゥエルビ
  type: BS
  channel: BS09_2
  serviceId: 222
- name: ＢＳスカパー！
  type: BS
  channel: BS11_0
  serviceId: 241
- name: ＢＳ釣りビジョン
  type: BS
  channel: BS11_2
  serviceId: 251
- name: ＢＳ日テレ
  type: BS
  channel: BS13_0
  serviceId: 141
- name: ＢＳ日テレ
  type: BS
  channel: BS13_0
  serviceId: 142
- name: ＢＳ日テレ
  type: BS
  channel: BS13_0
  serviceId: 143
- name: ＢＳフジ・１８１
  type: BS
  channel: BS13_1
  serviceId: 181
- name: ＢＳフジ・１８２
  type: BS
  channel: BS13_1
  serviceId: 182
- name: ＢＳフジ・１８３
  type: BS
  channel: BS13_1
  serviceId: 183
- name: ＢＳアニマックス
  type: BS
  channel: BS13_2
  serviceId: 236
- name: ＮＨＫＢＳ１
  type: BS
  channel: BS15_0
  serviceId: 101
- name: ＮＨＫＢＳ１
  type: BS
  channel: BS15_0
  serviceId: 102
- name: スターチャンネル２
  type: BS
  channel: BS15_1
  serviceId: 201
- name: スターチャンネル３
  type: BS
  channel: BS15_1
  serviceId: 202
- name: Ｊ　ＳＰＯＲＴＳ　４
  type: BS
  channel: BS19_0
  serviceId: 245
- name: Ｊ　ＳＰＯＲＴＳ　１
  type: BS
  channel: BS19_1
  serviceId: 242
- name: Ｊ　ＳＰＯＲＴＳ　２
  type: BS
  channel: BS19_2
  serviceId: 243
- name: ＷＯＷＯＷプラス
  type: BS
  channel: BS21_0
  serviceId: 252
- name: 日本映画専門ｃｈ
  type: BS
  channel: BS21_1
  serviceId: 255
- name: ＴＢＳチャンネル１
  type: CS
  channel: CS2
  serviceId: 296
- name: テレ朝チャンネル１
  type: CS
  channel: CS2
  serviceId: 298
- name: テレ朝チャンネル２
  type: CS
  channel: CS2
  serviceId: 299
- name: ディズニージュニア
  type: CS
  channel: CS2
  serviceId: 339

